### PR TITLE
Add scripts to pull data and re-generate Fig. 2, S2 and 4

### PR DESCRIPTION
**Pull request by trangdata**
I explained the need for a change of Figure 4 in #1. We can keep discussing to find the optimal way to visualize this, but I think the reader (and reviewers) are likely familiar with a feature importance plot, so this updated figure will require a lot less cognitive load than the current one with boxplots of replications for each pipeline.

For Fig. 2 (and S2 for Negative MSE), I wanted to avoid two things:
- histogram: because it's sensitive to bin width
- density plot: because we don't need to impose a distribution on this type of data to draw conclusion

I think plotting out all the data points with a beeswarm plot overlaying a light boxplot achieves this goal.

### CODE REVIEW

**Comment by jrm5100** [comment]
I do like the updated figure 2- I might just change "Real Data" to "Original Data" in the labels.

For figure 4, I think it isn't so clear-cut.

- I agree that the range of feature importance values for a given feature in a given pipeline may not so important since the distributions don't seem to be very interesting.  However, in some cases features may have small differences in medians (and therefore rank) but with distributions that greatly overlap.  For example, _TBXAR2_, _PELI2_, and _DMTF1_ for the biliruben phenotype.
- I think given unlimited space we would show a different feature importance plot for each of the top pipelines (which, from what I can find, would usually utilize barplots or histograms).  The convenience of the current plot is that it compacts this and groups the same bin together across different pipelines (conveying all of the same information except showing fewer bins).  Even this isn't showing the full picture though, as it would be useful to see how the importance of one feature correlates with the importance of others within the same replication.  Going back to the above example, it is possible that the replicate feature importance calculations emphasize only one of the three in any given replication.  Or there may be an additive effect.
- I'd describe the focus of the paper as a method of generating regression pipelines (specifically choosing sets of features rather than analyzing all features individually) and examining them to find potentially important relationships.  The most important insights are (1) whether the best pipelines repeatedly find the same features or are able to have good predictions based on different data and (2) how the different features are important in different pipelines- is it a single feature driving the prediction, one of several, etc.  For example, Absolute CD4 count pipeline 2 seems to use CPVL and NOP2 while pipeline 4 uses CPVL and SH3GLB1- this is probably because they use different feature sets- but they get similar scores.

What about something like your heatmap example in issue #1, but where each "block" is 10x10 pixels (or scaled larger) where pixel color corresponds to the median feature importance?  Essentially a higher resolution heatmap showing the individual feature importance scores in a grid (using color) rather than converting them to an average.  This would be more compact than the current plot and have the added benefit of showing differences in feature importance within the same feature importance replicate.  For example, maybe _PIK3R1_ is only important for Biliruben when _PYGM_ is not.  Or maybe they are always important together and some other less-important bins are used in other replications.  I could take a crack at that tomorrow or Thursday.

**Comment by trangdata** [comment]
Thank you for the feedback, @jrm5100. I made the changes in Fig. 2 according to your suggestion.

> a different feature importance plot for each of the top pipelines (which, from what I can find, would usually utilize barplots or histograms)

I think by barplots, you mean something like [this](https://www.researchgate.net/profile/Ashish_Dutt/publication/334130244/figure/fig1/AS:775720506757120@1561957589010/Feature-importance-plot.ppm). I just feel like the bars don't add much to the visualization. But we can do this.

> The most important insights are (1) whether the best pipelines repeatedly find the same features or are able to have good predictions based on different data and (2) how the different features are important in different pipelines- is it a single feature driving the prediction, one of several, etc. 

Thank you for clarifying this. Spelling this out helps me understand the goal better. I'm okay with sticking with feature importance score. I don't know if we should scale these somehow. I can try the heatmap again and see what we get.

**Comment by jrm5100** [comment]
## Figure 2

I think I'd swap the order of original and permuted.  I know from the perspective of the data original -> permuted makes sense, but from the perspective of the test (null -> hypothesis) it makes more sense to show permuted on left and original on right.

## Figure 4

I like the latest version.  However, fewer genes are shown so the results are different (requiring rewriting/researching some of the discussion.  Can we include the top 16?  It looks like the ranking order is almost identical to the original figure.

The label for the color should be "Median Permutation Feature Importance Score"

I realize the point of excluding the 4-10 pipelines for the plasma HIV portion.  We just need to make sure to include a note in the caption.

**Comment by trangdata** [comment]
> I know from the perspective of the data original -> permuted makes sense, but from the perspective of the test (null -> hypothesis) it makes more sense to show permuted on left and original on right.

This is exactly what I was debating in my head as well. I'll swap them.

> I like the latest version. However, fewer genes are shown so the results are different (requiring rewriting/researching some of the discussion. Can we include the top 16? It looks like the ranking order is almost identical to the original figure.

Done. However, as a note (for the potential revision), we should consider rescaling the importance score somehow (e.g., so that we have the scores vary from 0 to 1 for each phenotype).

> The label for the color should be "Median Permutation Feature Importance Score"

I'll change "Pipeline importance" to "Feature importance". We can elaborate on what this means in the caption and main text.

> I realize the point of excluding the 4-10 pipelines for the plasma HIV portion. We just need to make sure to include a note in the caption.

OK will do!

**Review by jrm5100 — APPROVED** [review]

**Pull request merged**
